So my name is Giulia Bruno, and I am associate professor at the department of management Production Engineering. Here, okay, there is the description of the course and the expected learning outcomes. All this information are available on the portal. There is the description of the course on the portal. More or less, I think that these things were already covered by the part of professor Cantamese.
So let's start from here. So the purposes of the course. Because until now, you have seen the first topic, the operation strategy. Then we cover all these other parts. So starting from today, we will talk about the formalism to represent the production processes, especially the parts related to the material flows.
Okay, so you probably have already seen other kinds of formalism related to the information to the representation of information flows, such as the flowchart, the UML diagrams and so on. Okay? So after a brief summary of this formalism, we see three other types of formalism that are the flow process chart, the value stream mapping and the IDEF zero. These are tools that probably you need if in your working careers you will need to represent the material flow processes. After that, we start the core of the course, that is the manufacturing systems modeling and analysis.
That basically is the application of the Q systems to the production systems, the Q theory to the production systems. So we see an introduction to the factory models with the terminology, the the KPIs, the basic sonotations and formulas, and then we extend the model to the factory, starting from the representation of a single workstation and then extending it to firstly to align our workstations, then a network of workstations, then a network able to process in multiproducts with different product types following different routing, and finally the batches. Maybe you have already seen part of this theory in other courses, but we start from zero, from scratch, and we introduce a specific terminology that maybe can be different from the one that you have already seen. And then in the last lesson, I also want to give you some so the basic concepts of discrete event simulation, because we will see that when the production system becomes more complex, it's not possible to model and analyze it only by using the analytical approach, so the formulas that we will see during the course. And thus, we needed to use a simulation software, okay?
So during the course, I will also show you some example of models developed in simulation software, but I don't ask you to learn the software, of course, but just to compare the results. So to see that for the simple examples that we analyze, we can solve them or by using the analytical formulas or by using the simulation software. Then if the model becomes too complex and we also need to add the transport, the operators and other things that we won't see, then the formulas are not enough, so we need software. And after that, also some concept about the industry four point zero, industry five point zero and machine learning applications in the manufacturing domain. Okay?
Because these are things that maybe are not covered by other courses, but it's important for you to know them, at least from a theoretical point of view, also for your future activities, for the thesis, the research projects, and so on. Okay? So this is the program of the following part, the remaining part of the course. Then just two words about the exam. Okay.
The exam is written, and it contains both numerical exercises and questions on more theoretical aspects. So there is a part, usually it's five questions, multiple choice questions, so theoretical questions or small exercises, and then a set of exercise or open questions for the remaining part. Okay. The numerical exercise and the theoretical questions can be integrated in the same exercise, and during the exam it's not possible to consult any support. Okay?
Here I will provide you directly the formulas that you need. Okay? So here I I just want to show you. This is the paper, the exam sheets. So you are sit down in your room and you will receive this paper.
At the beginning, you have the five multiple choice questions. So you read the text and select the right answer and report the letter of the correct answer in the first table here. And then then you have the exercises and the space, the white space where to write the answers. Okay? So you receive these set of papers, and you give back these exact set of papers.
Then we will during the course some example, okay, of exercises, and we'll do the exam simulation in in the end of the course, okay, as usual. In the end so in the last page, for instance, here, I report the formulas. Okay? So you don't need a separate formula sheets because I provide all the formulas that you need there directly on the exam paper. Okay?
Questions? You have two hours of time. So then if you have questions, we will discuss about the exam later. Okay? Okay.
Then about the material. So you have already have all the material by professor Cantamese. So you have his slides. Also, I have seen that he uploaded some example of questions for the exam. I will do the same.
So I upload week by week the material for my part of the lessons and for the practices, so all the exercises. Then the suggested books are the operation strategy by Slack and Lewis for the part of professor Cantamese. So if you wanted to so it's better not just to read the slide, but also consult a textbook. So this is this is his reference book. And for my part, we follow the Manufacturing Systems Modeling and Analysis by Carrie and Feldman, edited by Springer.
This is a book that you can if you search on the Internet, you can download it freely. And we follow from the second chapter. So the second chapter is the factory analysis. Then chapter three is the single workstation modeling and so on. So the list of topics reflects the index of this book starting from the second chapter.
Instead, for the initial part about the formalism, the ones that we see today and the next week, it's enough for the slide. And if you need additional material, just search for the name of formalism on Google and you can find other references. But there is not a single book covering all the formalism. Okay? So you are free to consult other sources also coming from the Internet.
Okay? Okay. Then scheduling contacts, you already known for the the theory. You have here our email contacts. Usually, on Thursday, apart this week, so on Thursday, we have the lessons.
And on Friday, we have the first part of the lesson with me and the second part of practice with my colleague, doctor Gabriel Antal, who is my assistant in this course, and he will assist you in solving the exercises. Okay? Usually, we follow the schedule. Then if there are changes, we will see week by week. Also because in this course, we have the problem of the calendar.
So we we lose a lot of lessons due to the holidays of Easter of the April 25 and the May 1. We are very unlucky with this course because we lose a lot of lesson. And in the calendar, we cannot cover the whole amount of lessons. So I will ask you to do so to find some additional slots to to do the the lessons that we we that are missing in the calendar. We will see how.
So or online or maybe on Saturday because we we don't have any alternatives because the rooms are full during the week. Okay. So we will see it. Let's now start and see. We will try to cover everything.
Then we also have a part time student. So you know the the part time collaboration of the students that assist during the course. So we have Tommaso Vazica, who is a student from the past year that applied for the part time collaboration. So if you are interested in this course, you can apply for the next year. And he will be present during practice hours later, so in in the end of the course.
So if you have doubts or questions in addition to to my colleague, you can ask him to help you solving the exercises. Okay? Any question? Everything clear? Mhmm.
Okay. As also professor Cantamessa said, I record the lesson as he said, so it's a best effort. So let's hope that everything is working. Sometimes I don't record in the right way both of the audio, the video, but okay. Let's assume that everything is fine, so I will upload the lesson as soon as possible.
Okay. So now let's finish this this first set of slides, finishing the introduction to the to the course. Here, probably, the the things that I say, you you already know them because we have already here the the lessons of professor Cantamese. In this way, you have exactly the same material of the other course. Okay?
So I leave you also these slides even if maybe they are redundant. So in this course, we are focused on the analysis and management of production systems. During the course, we mainly refer to the manufacturing systems. But always keep in mind that when talking about production system, we mean also not only manufacturing because the the concepts that we see applied to the manufacturing system can be applied also to other kinds of systems. But all the example that we use are taken from the manufacturing domain.
So here we define the plant. Here there is an example of a map of the plant that is a space with several machines placed of different types, which execute different operations on different product. And in order to produce a product, we define the flow among the machines, starting from the raw material, then the order of the list of operations, and thus machine, machines that are used to produce the final product. So our objective is so to form the responsibility of management of the need. So you if you will go to work in such companies.
So you will be able to analyze a manufacturing plant. It is the place where the manufacturing processes are executed and implemented in order to manufacture the final products, and also find the best way of manage the personnel and the machines that operate in the plant. Here the kind of production is called discrete production as in contrast with the continuous production. The example that we see can be applied only for discrete production, so where we can identify the units of products and so we are not dealing with liquid such as the ones used in the chemical industries and so on. Okay?
This is the model used in the automotive, electronics, and so on sectors. So the processes are dedicated to the production of distinct units. Then how we can manage the production system? Well, we address these three phases, so to analyze, to evaluate, and then to manage. So analyzing a production phase means understand the structure of the production process and also being able of identify all the elements that are involved in the process.
And then evaluate. So the final aim of all this course is to be able and to see which are the formulas that we can use to evaluate specific KPIs for the production. Starting from the data collected from the plant. Okay? So an example can be, okay, I want to compute which is the average waiting time of my products inside the plant.
Okay? Because this is an important KPI. So the number of waiting items or the the average waiting times is a KPI relevant for the company and tends to so the objective is to reduce this time or this number of items. Or the throughput, so you will be able to compute the throughput of a line or of a network, over stations, and the throughput is another KPI for the production and so on. So firstly, analyze, being able to analyze the production system, also to describe it in the better way by using the formalism.
So this is why we start by seeing which are the formalism that can be used and then to evaluate the system in terms of defining which are the KPIs and the formulas to compute them. And then these things can be used to manage the production system. But to manage the production system, there are other courses and other techniques that are not covered here. So when we talk about evaluating performance, what do we mean? Firstly, to evaluate the structure, for instance, by identifying the critical points.
For instance, to be able to identify the bottleneck of the systems. So the the workstation that are slower than the others and does limit the throughput of the system. And then when we talk about performances, here we have some example. So for instance okay. No.
Here, only have the the type of performance index that are efficiency, effectiveness, and economic convenience. About these three types, we mainly focus on the first one. So the efficiency of using the resources. This is a concept related to the utilization of the resources, the number of items inside the plant, the throughput of the system and so on. Then, of course, the efficiency is related also to the effectiveness.
The effectiveness is the inspection of the customer about the final products. So it's more related to the quality of the product. This is related to the efficiency, but we here, we have other kinds of KPI that we want to compute. And finally, again, the economic convenience. Also, the economic convenience is related to the efficiency of the system.
But during the course, we won't talk about costs. We stop at the time analysis, so the analysis of times, without translating them into cost. So here now, let's see some example of the critical points. So we can have the bottleneck. It means a resource with the lowest production rate that usually also corresponds to the resource with the highest utilization.
We will define more formally these terms later. But so production rate means the rate of production. So it's the quantity of final products produced in the time unit. So the production rate is a concept equal to the throughput or the highest utilization. The utilization is a value between zero and one, usually expressed in a percentage.
That means the percentage of time that resource is used. Then the critical path, so the longest path from the raw material to the final product, because it determines the longest cycle time, so the time in which a product remain in the system, and the unbalanced units, So the resources with different production rates that, again, affect the throughput of the system. Then when we talk about the KPIs okay, we have already cited them. So the throughput, it's defined as the number of final products that exit from the system per time unit. Okay?
So remember the time the unit of measure of the throughput. So it's the number of products per time units. So the throughput is, okay, this system produces 10 items per hour or 100 items per day, not only 100, okay? 100 is not a measure of a throughput. Always remember that it's a quantity per unit of time.
Then so the throughput is a KPI because it should be maximized. So the company wants to produce as much as possible of products in the time unit. Then instead, the cycle time is defined at the time in which the product remains inside the system. K? So for each product, we can measure the time instant in which it arrives, not the final product, but the raw materials that are needed to produce the final product, and the time instant in which the final product is produced, so exit the system.
And this time length is the cycle time of this product. We are interested in the average cycle time of the system, and this is another KPI. The cycle time needs to be maximized or minimized minimized. And then the working process. The working process is defined as the number of products which are present in the system at the same time.
Okay? So the the working process is used to measure not only the the product that are in the processing state, so they are inside the workstation, a machine and are processed, but also the items that are waiting that are waiting that the machine is free, is idle in order to process them. And also the working process needed to be minimized. Why it's important to minimize the work in process? So the number of items in the plant at the same time.
What do you think? Why we cannot leave a lot of items inside our plant? Which is the problem? Space, storage costs, exactly, transportation costs. Okay.
So if you have a lot of items, it means that you need the space to store them. This space has a cost. And then you are involving more people, more resources transport them from one workstation to another. So the WIP is another KPI because the objective is to minimize the WIP, especially because it's related to the waiting items. So the items are there, but they are just waiting something.
So this is not a value for a company. And finally, the utilization. So, again, the utilization is the percentage of time that the machine is processing, is doing something, so not only processing. It's so the the percentage of time that the machine is not idle. So it's processing or in the setup or is in the breakdown state, okay, under repair.
So the machine is doing something. Instead, the utilization needs to be maximized. So if we have the resources, then we need to use them. Otherwise, again, it's a cost that is not covered by production. Even if we will see the relationship also between the utilization of a resource and the number of items waiting.
Because if the resource is full, so its utilization is near 100%, well, it means that it's more probable that when an item arrives at this workstation, it has to wait. Okay? So if the utilization is very high, then we expect to have more items waiting in the queue before the workstation. So we need to to balance these things. Okay?
Okay. And so this is why we follow these these steps in our course. So we start by describing the production systems and identify its elements. And for this first step we need the formalism to represent the processes. Then we see the formal models to represent the production systems, so the mathematical formulas.
And then we will use these formulas to estimate the critical points of the system and evaluate the KPIs, So the cycle time, the working process, the throughput, and the utilization by using at the beginning the quantitative models, and then when the system becomes too complex, the simulations. Then there is the last step that is evaluate the results. So once we have computed the KPIs, then we need a benchmarking. So understand if the KPIs are good or not. But this is a step more related to the company, to the specific company, the specific domains.
So we we won't cover this fourth point in the course. So here, talking about the elements of the production systems or the manufacturing systems more correctly. So when we talk about a manufacturing systems, which are the main elements that you think about? We have already mentioned all of them during the speech. So when talking about the manufacturing systems, which are the main elements involved in the system?
Workstations? Label. Label. Labels or what? Or products?
Okay. Working. Yes. Then the the product, other things, machines, Raw materials. Yep.
Resources more in general. Yes. So not only machines, also the tools. Resources is a very general concept. It involves also the the people.
Another thing that we mentioned when talking about the WIP, storage, transportation, the maintenance. Exactly. So all these things so when talking about the manufacturing systems, probably we we think about all these things. The machines such as this red welding machine here, then the raw material such as the metal sheets, the components on or the final products, the people, so the operators that work in the plant, the storage, so the both the warehouses, the big warehouses for the raw material and for the the final products, but also the inventory, the small inventories near the machines. And then the transport, so for instance, the the automatic guided vehicles and so on.
The robots, the the robotic arms that are parts of the machines and so on. So in a manufacturing systems, we have a lot of elements. But we cannot address the modeling of all of them. Otherwise, the system and the model becomes too complex. So we will focus on these few elements in our analysis.
So the products that are made of components and raw materials, but for us the our unit is the product. Then the operations, So in this case, we call operations, so don't be confused by this term. So operation here means the activities, the technological processes. So we have a lot of synonyms for this term. So when we talk about operations, we mean the manufacturing operations, so the welding operation, the assembly operation, painting operation and so on.
So the operations are the activities done on the machines of the plant to transform a product and the resources to perform the operations that are the workstations. Inside the workstation we have the machines. So for us the resources basically means mean the machines. We we don't address the problem of the operators. Okay?
The operators working on the machines. If the operation is completely manual, then the operator is at the same level of the machine. Okay? And the relationships among these elements. Okay?
